# Generated by Django 3.2 on 2021-06-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210614_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='author_name',
            field=models.CharField(max_length=100),
        ),
    ]
