# Generated by Django 3.2 on 2021-06-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_log_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='session',
            field=models.CharField(max_length=8),
        ),
    ]
